import { describe, it, expect, vi } from 'vitest';
import {
  VideoGenerationService,
  validateVideoPrompt,
  mapProviderErrorToApplicationError,
} from './video-service';

describe('AI Video Generation Service Suite', () => {
  it('TEST 1: generates video for "Create a premium cinematic product video for a luxury men\'s watch."', async () => {
    const res = await VideoGenerationService.generateVideo({
      prompt: "Create a premium cinematic product video for a luxury men's watch.",
      style: 'Cinematic',
      aspectRatio: '16:9',
      duration: '10s',
    });

    expect(res.success).toBe(true);
    if (res.success) {
      expect(res.type).toBe('video');
      expect(res.video_url).toBeTruthy();
      expect(res.thumbnail_url).toBeTruthy();
      expect(res.status).toBe('completed');
    }
  });

  it('TEST 2: generates clean video for "Create a premium football achievements visual."', async () => {
    const res = await VideoGenerationService.generateVideo({
      prompt: 'Create a premium football achievements visual.',
      style: 'Cinematic',
      aspectRatio: '16:9',
      duration: '10s',
    });

    expect(res.success).toBe(true);
    if (res.success) {
      expect(res.type).toBe('video');
      expect(res.video_url).toBeTruthy();
    }
  });

  it('TEST 3: handles provider temporarily unavailable cleanly without raw provider error', async () => {
    const res = await VideoGenerationService.generateVideo({
      prompt: 'Cinematic product tour for modern workspace',
      mockFailure: 'temporary_unavailable',
    });

    expect(res.success).toBe(false);
    if (!res.success) {
      expect(res.code).toBe('PROVIDER_UNAVAILABLE');
      expect(res.message).toBe('Video generation is temporarily unavailable. Please try again.');
      expect(res.suggestedAction).toBe('try_again');
      // Must not contain raw stack trace or raw JSON
      expect(res.message).not.toContain('503');
    }
  });

  it('TEST 4: handles content policy / third-party rejection cleanly with Edit Prompt action and zero silent rewrite', async () => {
    // 4a. Simulated raw provider third-party refusal
    const res = await VideoGenerationService.generateVideo({
      prompt: 'Action highlights for championship tournament',
      mockFailure: 'policy_rejection',
    });

    expect(res.success).toBe(false);
    if (!res.success) {
      expect(res.code).toBe('PROVIDER_REJECTED');
      expect(res.message).toBe("This video concept can't be generated by the current provider. Try editing the prompt.");
      expect(res.suggestedAction).toBe('edit_prompt');
      // Crucial: Must NEVER contain the raw refusal string
      expect(res.message).not.toContain('interests of third-party content providers');
    }

    // 4b. Pre-flight celebrity / restricted likeness rejection
    const celebRes = await VideoGenerationService.generateVideo({
      prompt: 'cristiano achievements reel with trophy celebration',
    });

    expect(celebRes.success).toBe(false);
    if (!celebRes.success) {
      expect(celebRes.code).toBe('PROVIDER_REJECTED');
      expect(celebRes.suggestedAction).toBe('edit_prompt');
    }
  });

  it('TEST 5: produces video metadata ready for Content Library integration', async () => {
    const res = await VideoGenerationService.generateVideo({
      prompt: 'Futuristic AI software dashboard interaction in 4k',
      title: 'AI Dashboard Demo',
      duration: '10s',
      aspectRatio: '16:9',
      resolution: '1080p',
    });

    expect(res.success).toBe(true);
    if (res.success) {
      expect(res.title).toBe('AI Dashboard Demo');
      expect(res.type).toBe('video');
      expect(res.video_url).toMatch(/\.mp4$/);
      expect(res.created_at).toBeTruthy();
      expect(res.status).toBe('completed');
    }
  });

  it('TEST 6: pre-flight prompt validator rejects empty prompts or unsupported aspect ratios', () => {
    const emptyCheck = validateVideoPrompt({ prompt: '' });
    expect(emptyCheck.valid).toBe(false);
    expect(emptyCheck.error?.code).toBe('INVALID_REQUEST');

    const shortCheck = validateVideoPrompt({ prompt: 'ab' });
    expect(shortCheck.valid).toBe(false);

    const ratioCheck = validateVideoPrompt({
      prompt: 'Valid video prompt for brand showcase',
      aspectRatio: '21:9' as any,
    });
    expect(ratioCheck.valid).toBe(false);
    expect(ratioCheck.error?.technicalDetail).toContain('Unsupported aspect ratio');
  });

  it('TEST 7: maps network error and timeout to distinct, user-friendly messages', () => {
    const netErr = mapProviderErrorToApplicationError(new Error('fetch failed: ECONNREFUSED'), {
      provider: 'openai_sora',
      model: 'sora-1.0',
      stage: 'submission',
    });
    expect(netErr.code).toBe('NETWORK_ERROR');
    expect(netErr.message).toBe('Connection to the video generation service failed.');

    const timeoutErr = mapProviderErrorToApplicationError(new Error('Gateway Timeout'), {
      provider: 'openai_sora',
      model: 'sora-1.0',
      stage: 'generation',
    });
    expect(timeoutErr.code).toBe('TIMEOUT');
    expect(timeoutErr.message).toBe('Video generation is taking longer than expected. You can check again shortly.');
  });
});
