-- ============================================================
-- 077 — salary fields on employee_profiles.
--
-- Payroll processing needs a per-employee salary source.
-- employee_profiles is the live employees table (keyed by
-- workspace_member_id) but carries no amounts — only a free-text
-- salary_grade. These monthly amounts mirror the payslips columns
-- so a payslip is generated by copying them and applying period
-- deductions (approved salary advances).
--
-- Additive and idempotent; safe to run before or after 075/076.
-- ============================================================

ALTER TABLE public.employee_profiles
  ADD COLUMN IF NOT EXISTS basic_salary       NUMERIC NOT NULL DEFAULT 0 CHECK (basic_salary >= 0),
  ADD COLUMN IF NOT EXISTS hra                NUMERIC NOT NULL DEFAULT 0 CHECK (hra >= 0),
  ADD COLUMN IF NOT EXISTS special_allowance  NUMERIC NOT NULL DEFAULT 0 CHECK (special_allowance >= 0),
  ADD COLUMN IF NOT EXISTS pf_deduction       NUMERIC NOT NULL DEFAULT 0 CHECK (pf_deduction >= 0),
  ADD COLUMN IF NOT EXISTS professional_tax   NUMERIC NOT NULL DEFAULT 0 CHECK (professional_tax >= 0),
  ADD COLUMN IF NOT EXISTS tds_deduction      NUMERIC NOT NULL DEFAULT 0 CHECK (tds_deduction >= 0);

COMMENT ON COLUMN public.employee_profiles.basic_salary IS
  'Monthly amounts consumed by payroll processing (payslip generation).';
