create table if not exists public.webhook_debug_log (
  id         bigint generated by default as identity primary key,
  method     text    not null,
  headers    jsonb   not null default '{}'::jsonb,
  body       jsonb,
  raw_body   text,
  note       text,
  created_at timestamp with time zone default now()
);
